### ISSUE TITLE
UnboundLocalError: local variable 'prefix' referenced before assignment

### ISSUE THREAD

**Issue by YoussofH** [jakbin/django-tor#1]
**Describe the bug**
The runserver command won't launch the server due to an error in the function "get_resource_path". I guess the python code fails to get the right prefix of my OS.

**How to reproduce**
I have a windows 10 simply followed the README procedure.

**Expected behavior**
Run server normally.

**Traceback**
```python
> python manage.py runserver --noreload
Traceback (most recent call last):
  File "manage.py", line 29, in <module>
    main()
  File "manage.py", line 14, in main
    port = run_with_tor()
  File "venv\lib\site-packages\django_tor\django_tor.py", line 7, in run_with_tor
    onion = Onion()
  File "venv\lib\site-packages\django_tor\onion.py", line 121, in __init__
    (self.tor_path, self.tor_geo_ip_file_path, self.tor_geo_ipv6_file_path) = common.get_tor_paths()
  File "venv\lib\site-packages\django_tor\common.py", line 57, in get_tor_paths
    base_path = os.path.join(os.path.dirname(os.path.dirname(get_resource_path(''))), 'tor')
  File "venv\lib\site-packages\django_tor\common.py", line 47, in get_resource_path
    print("Prefix is:",prefix)
UnboundLocalError: local variable 'prefix' referenced before assignment
```

**manage.py**

```python
#!/usr/bin/env python
import os
import sys

from django_tor import run_with_tor
from django.core.management.commands.runserver import Command as runserver

def main():
    os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'dhive.settings')
    
    port = run_with_tor()
    runserver.default_port = str(port)
    
    try:
        from django.core.management import execute_from_command_line
    except ImportError as exc:
        raise ImportError(
            "Couldn't import Django. Are you sure it's installed and "
            "available on your PYTHONPATH environment variable? Did you "
            "forget to activate a virtual environment?"
        ) from exc
    execute_from_command_line(sys.argv)

if __name__ == '__main__':
    main()
```

**Comment by jakbin** [comment]
i can't find ` print("Prefix is:",prefix)` in common.py.

**Comment by YoussofH** [comment]
> i can't find ` print("Prefix is:",prefix)` in common.py.

I was debugging the prefix variable so i added that line of code `print("Prefix is:",prefix)` before the return statement, yet prefix was blank!

**Comment by YoussofH** [comment]
I assume @jakbin you are working to solve the problem, I am working on solving it too. I guess the moral of the error is the path of tor command on windows system, that is then joined with "share" directory. Am i right?

**Comment by jakbin** [comment]
Without this it's working or not ?

I am using linux . I didn't got this error .

**Comment by YoussofH** [comment]
It's not working neither ways. The tor project is installed normally. But the question is, should there be known paths to the tor executables? and should I add them to the environment variables?

**Comment by jakbin** [comment]
Remove `print("Prefix is:",prefix)` and then tell me where is error .

**Comment by YoussofH** [comment]
Bruh here is the error:
```python
> python manage.py runserver --noreload
Traceback (most recent call last):
  File "manage.py", line 29, in <module>
    main()
  File "manage.py", line 14, in main
    port = run_with_tor()
  File "venv\lib\site-packages\django_tor\django_tor.py", line 7, in run_with_tor
    onion = Onion()
  File "venv\lib\site-packages\django_tor\onion.py", line 121, in __init__
    (self.tor_path, self.tor_geo_ip_file_path, self.tor_geo_ipv6_file_path) = common.get_tor_paths()
  File "venv\lib\site-packages\django_tor\common.py", line 57, in get_tor_paths
    base_path = os.path.join(os.path.dirname(os.path.dirname(get_resource_path(''))), 'tor')
UnboundLocalError: local variable 'prefix' referenced before assignment
```

**Comment by YoussofH** [comment]
The problem is within the `get_tor_paths()` function:
```python
def get_tor_paths():
    p = get_platform()
    if p == 'Linux':
        tor_path = '/usr/bin/tor'
        tor_geo_ip_file_path = '/usr/share/tor/geoip'
        tor_geo_ipv6_file_path = '/usr/share/tor/geoip6'
    elif p == 'Windows':
        base_path              = os.path.join(os.path.dirname(os.path.dirname(get_resource_path(''))), 'tor') # this line is calling "get_resource_path()" which is causing the error
        tor_path               = os.path.join(os.path.join(base_path, 'Tor'), "tor.exe")
        tor_geo_ip_file_path   = os.path.join(os.path.join(os.path.join(base_path, 'Data'), 'Tor'), 'geoip')
        tor_geo_ipv6_file_path = os.path.join(os.path.join(os.path.join(base_path, 'Data'), 'Tor'), 'geoip6')
    elif p == 'Darwin':
        base_path = os.path.dirname(os.path.dirname(os.path.dirname(get_resource_path(''))))
        tor_path               = os.path.join(base_path, 'Resources', 'Tor', 'tor')
        tor_geo_ip_file_path   = os.path.join(base_path, 'Resources', 'Tor', 'geoip')
        tor_geo_ipv6_file_path = os.path.join(base_path, 'Resources', 'Tor', 'geoip6')

    return (tor_path, tor_geo_ip_file_path, tor_geo_ipv6_file_path)
```

The problem is with the `base_path`. If there is an example of how it should look I can hardcode the path, but that won't solve the problem for other windows users.

**Comment by jakbin** [comment]
Try these changes https://github.com/onionshare/onionshare/blob/v1.3/onionshare/common.py

**Comment by YoussofH** [comment]
The server is up and running successfully after i hard coded the base_path of the tor directory. I am facing this error `DisallowedHost` of the newly generated onion link. Is there a way to add onion url to the allowed hosts?

**Comment by jakbin** [comment]
> Try these changes https://github.com/onionshare/onionshare/blob/v1.3/onionshare/common.py 

Did you try this @YoussofH ?

**Comment by jakbin** [comment]
> The server is up and running successfully after i hard coded the base_path of the tor directory. I am facing this error `DisallowedHost` of the newly generated onion link. Is there a way to add onion url to the allowed hosts?

In setting.py set allowed_host = ['*']

**Comment by YoussofH** [comment]
In the README file you mentioned that we have to append the following to manage.py
```python
from django_tor import run_with_tor

port = run_with_tor()

from django.core.management.commands.runserver import Command as runserver
runserver.default_port = str(port)
```
the tor service is launched even when I want to makemigrations, migrate and other sys arguments.

There should be a way to run tor service sololey from the sys arguments.

Goal: Run tor service only when `runserver` is supplied rather when i run manage.py everytime.
Thanks in advance!

**Comment by YoussofH** [comment]
> > The server is up and running successfully after i hard coded the base_path of the tor directory. I am facing this error `DisallowedHost` of the newly generated onion link. Is there a way to add onion url to the allowed hosts?
> 
> In setting.py set allowed_host = ['*']

As far as i know using wildcard in the allowedhosts is not secure. There should be a way to inject the generated onion url after the tor service runs, am I right?

**Comment by jakbin** [comment]
> > In setting.py set allowed_host = ['*']
> 
> As far as i know using wildcard in the allowedhosts is not secure. There should be a way to inject the generated onion url after the tor service runs, am I right?

upgrade django-tor to new version and read new readme.
@YoussofH

**Comment by jakbin** [comment]
> 
> > > In setting.py set allowed_host = ['*']
> > 
> > As far as i know using wildcard in the allowedhosts is not secure. There should be a way to inject the generated onion url after the tor service runs, am I right?
> 
> upgrade django-tor to new version and read new readme.

@YoussofH

**Comment by jakbin** [comment]
I have used base source code of onionshare . For mac and windows, he provide tor binary With installer package.

But in flask-tor tor binary not available .
@YoussofH

**Comment by jakbin** [comment]
@YoussofH install win-tor-resources with pip. use this new common.py

[common.py.zip](https://github.com/jakbin/django-tor/files/8974979/common.py.zip)

**Comment by Aditya-Rajgor** [comment]
> The server is up and running successfully after i hard coded the base_path of the tor directory. I am facing this error `DisallowedHost` of the newly generated onion link. Is there a way to add onion url to the allowed hosts?

2024 facing the same issue, can you tell me what exact changes did you made to base_path

**Comment by Aditya-Rajgor** [comment]
Finally solved it by hard coding the paths, 

Anyone who is having the same on windows, here is the solution, 

## common.py
```python
base_path = "C:\\Program Files\\OnionShare\\lib\\onionshare\\resources\\tor"

tor_geo_ip_file_path   = os.path.join(base_path, 'geoip')
tor_geo_ipv6_file_path = os.path.join(base_path, 'geoip6')
tor_path               = os.path.join(base_path,  "tor.exe")
```

## manage.py
```python
#!/usr/bin/env python
"""Django's command-line utility for administrative tasks."""
import os
import sys
from django_tor import run_with_tor
from django.core.management.commands.runserver import Command as runserver


host, port = run_with_tor()
runserver.default_port = str(port)


def main():
    """Run administrative tasks."""
    os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'portfolio_website.settings')

    try:
        from django.core.management import execute_from_command_line
    except ImportError as exc:
        raise ImportError(
            "Couldn't import Django. Are you sure it's installed and "
            "available on your PYTHONPATH environment variable? Did you "
            "forget to activate a virtual environment?"
        ) from exc
    execute_from_command_line(sys.argv)


if __name__ == '__main__':
    main()

```
